assignment2:
  hosts:
    instance1:
      ansible_ssh_private_key_file: "~/.ssh/a2_key"
      ansible_user: ubuntu
      ansible_host: 3.91.170.130
    instance2:
      ansible_ssh_private_key_file: "~/.ssh/a2_key"
      ansible_user: ubuntu
      ansible_host: 54.87.190.205
