assignment2:
  hosts:
    instance1:
      ansible_ssh_private_key_file: "~/.ssh/a2_key"
      ansible_user: ubuntu
      ansible_host: 44.200.6.21
    instance2:
      ansible_ssh_private_key_file: "~/.ssh/a2_key"
      ansible_user: ubuntu
      ansible_host: 44.204.169.12
