- name: Install packages
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: yes

- name: Install Bun
  command: "curl -fsSL https://bun.sh/install | bash"

- name: Add Caddy GPG key
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add Caddy repository to sources
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Caddy
  become: yes
  apt:
    name: caddy
    state: present
